<?php

namespace AppBundle\Repository;

/**
 * CharacterLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterLikeRepository extends BaseRepository
{
}
