<?php

namespace AppBundle\Repository;

/**
 * CharacterSerifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterSerifRepository extends \Doctrine\ORM\EntityRepository
{
}
