<?php

namespace AppBundle\Repository;

/**
 * CharacterDislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterDislikeRepository extends BaseRepository
{
}
