<?php

namespace AppBundle\Repository;

/**
 * CharacterRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRoleRepository extends BaseRepository
{
}
