<?php

namespace AppBundle\Repository;

/**
 * CharacterBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterBaseRepository extends BaseRepository
{
}
