<?php

namespace AppBundle\Repository;

/**
 * CharacterAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
