<?php

namespace AppBundle\Repository;

/**
 * CharacterCatchPhraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterCatchPhraseRepository extends BaseRepository
{
}
