<?php

namespace AppBundle\Repository;

/**
 * EgsBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsBrandRepository extends BaseRepository
{
}
