<?php

namespace AppBundle\Repository;

/**
 * EgsBrandExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsBrandExtRepository extends BaseRepository
{
}
