<?php

namespace AppBundle\Repository;

/**
 * EgsGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsGameRepository extends \Doctrine\ORM\EntityRepository
{
}
