<?php

namespace AppBundle\Repository;

/**
 * EgsGameYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsGameYearRepository extends BaseRepository
{
    /**
     * @param int $page
     * @param int $limit
     * @param array $sortAndOrders
     * @param array $filters
     *
     * @return array
     */
    public function getList($page = 1, $limit = 0, $sortAndOrders = array(), $filters = array())
    {
        $year = empty($filters['year']) ? null : $filters['year'];
        $order = 'ASC';
        $em = $this->getEntityManager();
        $dql = "SELECT o FROM {$this->_entityName} o ORDER BY o.year {$order}";
        $query = $em->createQuery($dql);
        $records = $query->getArrayResult();
        if (empty($records)) {
            return array();
        }
        // 選択情報を付与
        $results = $this->mergeWhichSelected($records, $year);
        return $results;
    }
}
