<?php

namespace AppBundle\Repository;

/**
 * EgsGameYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsGameYearRepository extends BaseRepository
{
    /**
     * @param string $year
     * @param string $month
     * @param int $page TODO:実装
     * @param string $sort TODO:実装
     * @param string $order
     * @param int $includeDeleted TODO:実装
     * @param string $keyword TODO:実装
     *
     * @return array
     */
    public function getList($year = '', $month = '', $page = 0, $sort = '', $order = 'asc', $includeDeleted = 0, $keyword = '')
    {
        $em = $this->getEntityManager();
        $dql = "SELECT o FROM {$this->_entityName} o ORDER BY o.year {$order}";
        $query = $em->createQuery($dql);
        $records = $query->getArrayResult();
        if (empty($records)) {
            return array();
        }
        // 選択情報を付与
        $results = $this->mergeWhichSelected($records, $year);
        return $results;
    }
}
