<?php

namespace AppBundle\Repository;

/**
 * EgsGameExtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsGameExtRepository extends \Doctrine\ORM\EntityRepository
{
}
