<?php

namespace AppBundle\Repository;

/**
 * EgsGameRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgsGameRepository extends BaseRepository
{
    /**
     * @param string $year
     * @param string $month
     * @param int $page TODO:実装
     * @param string $sort TODO:実装
     * @param string $order
     * @param int $includeDeleted TODO:実装
     * @param string $keyword TODO:実装
     *
     * @return array
     */
    public function getList($year = '', $month = '', $page = 0, $sort = '', $order = 'asc', $includeDeleted = 0, $keyword = '')
    {
        $em = $this->getEntityManager();
        if (empty($year) && empty($month)) {
            // 全件
            $dql = "SELECT o FROM {$this->_entityName} o ORDER BY o.releaseYmd {$order}";
            $query = $em->createQuery($dql);
        } else {
            if (empty($month)) {
                $year = date('Y', strtotime($year . '-01-01'));
                // 年別
                $needle = $year . '-%';
                $dql = "SELECT o FROM {$this->_entityName} o WHERE o.releaseYmd LIKE :releaseYmd ORDER BY o.releaseYmd {$order}";
                $query = $em->createQuery($dql)->setParameter('releaseYmd', $needle);
            } else {
                $year = date('Y', strtotime($year . '-01-01'));
                $month = date('m', strtotime($year . '-' . $month . '-01'));
                // 年月別
                $needle = $year . '-' . $month . '-%';
                $dql = "SELECT o FROM {$this->_entityName} o WHERE o.releaseYmd LIKE :releaseYmd ORDER BY o.releaseYmd {$order}";
                $query = $em->createQuery($dql)->setParameter('releaseYmd', $needle);
            }
        }
        return $query->getArrayResult();
    }
}
