<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Game;

/**
 * EgsGameExtRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends BaseRepository
{
    /**
     * @param string $year
     * @param string $month
     * @param int $page TODO:実装
     * @param string $sort TODO:実装
     * @param string $order
     * @param int $includeDeleted TODO:実装
     * @param string $keyword TODO:実装
     *
     * @return array
     */
    public function getList($year = '', $month = '', $page = 0, $sort = '', $order = 'asc', $includeDeleted = 0, $keyword = '')
    {
        // EgsGame
        $em = $this->getEntityManager();
        $egsGameRepository = $em->getRepository('AppBundle:EgsGame');
        $egsGames = $egsGameRepository->getList($year, $month, $page, $sort, $order, $includeDeleted, $keyword);
        if (empty($egsGames)) {
            return array();
        }
        // Game
        $egsGameIds = array_column($egsGames, 'id');
        $games = $this->findBy(array('egsGameId' => $egsGameIds));
        $games = $this->convertEntitiesToAssoc($games, 'egsGameId');
        // FIXME: 対応するデータがなかった場合は、どうする？
        // EgsGame + Game
        $list = array();
        foreach ($egsGames as $egsGame) {
            $temp = $egsGame;
            $temp['egsGameId'] = empty($games[$egsGame['id']]['egsGameId']) ? false : $games[$egsGame['id']]['egsGameId'];
            $temp['isDone'] = empty($games[$egsGame['id']]['isDone']) ? false : $games[$egsGame['id']]['isDone'];
            $temp['isDeleted'] = empty($games[$egsGame['id']]['isDeleted']) ? false : $games[$egsGame['id']]['isDeleted'];
            $list[] = array_merge($egsGame, $games[$egsGame['id']]);
        }
        return $list;
    }

    /**
     * @param array $egsGames
     *
     * @return bool
     */
    public function upsertFromEgsGame($egsGames = array())
    {
        if (empty($egsGames)) {
            return false;
        }
        $egsGamesIds = array_column($egsGames, 'id');
        $implodeEgsGameIds = implode(',', $egsGamesIds);
        $em = $this->getEntityManager();
        $dql = <<<EOM
SELECT o 
FROM {$this->_entityName} o 
WHERE o.egsGameId IN ({$implodeEgsGameIds})
EOM;
        $query = $em->createQuery($dql);
        $oldGames = $query->getArrayResult();
        if (empty($oldGames)) {
            // 全件新規登録
            $newEgsGameIds = $egsGamesIds;
        } else {
            // 一部新規登録
            $oldGameEgsGameIds = array_column($oldGames, 'egsGameId');
            $newEgsGameIds = array_diff($egsGamesIds, $oldGameEgsGameIds);
        }
        // 飛んできたデータを新規登録分だけにする
        $newRecords = array();
        foreach ($egsGames as $egsGame) {
            if (in_array($egsGame['id'], $newEgsGameIds)) {
                $newRecords[] = $egsGame;
            }
        }
        if (empty($newRecords)) {
            // 新規登録なし
            return true;
        }
        foreach ($newRecords as $record) {
            $entity = new Game();
            $entity->setEgsGameId($record['id']);
            $entity->setIsDone(false);
            $entity->setIsDeleted(false);
            $em->persist($entity);
        }
        $em->flush();
        $em->clear();
        return true;
    }

    /**
     * @param int $egsGameId
     *
     * @return array
     */
    public function toggleIsDone($egsGameId = 0)
    {
        if (empty($egsGameId)) {
            return array();
        }
        $em = $this->getEntityManager();
        $game = $this->findOneBy(array('egsGameId' => $egsGameId));
        $newState = empty($game->getIsDone()) ? true : false;
        $game->setIsDone($newState);
        $em->merge($game);
        $em->flush();
        $em->clear();
        $returnValue = $this->convertEntityToAssoc($game, 'id');
        if (empty($returnValue[$game->getId()])) {
            return array();
        }
        return $returnValue[$game->getId()];
    }

    /**
     * @param int $egsGameId
     *
     * @return array
     */
    public function toggleIsDeleted($egsGameId = 0)
    {
        if (empty($egsGameId)) {
            return array();
        }
        $em = $this->getEntityManager();
        $game = $this->findOneBy(array('egsGameId' => $egsGameId));
        $newState = empty($game->getIsDeleted()) ? true : false;
        $game->setIsDeleted($newState);
        $em->merge($game);
        $em->flush();
        $em->clear();
        $returnValue = $this->convertEntityToAssoc($game, 'id');
        if (empty($returnValue[$game->getId()])) {
            return array();
        }
        return $returnValue[$game->getId()];
    }

}
