<?php

namespace AppBundle\Repository;

/**
 * GenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderRepository extends BaseRepository
{
    /**
     * @param null $needle
     *
     * @return array
     */
    public function getList($needle = null)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT o FROM AppBundle:Gender o";
        $query = $em->createQuery($dql);
        $records = $query->getArrayResult();
        // 選択情報を付与
        $results = $this->mergeWhichSelected($records, $needle);
        return $results;
    }
}
